seed: null
prediction_length: 32
context_length: 48
train_epochs: 50
quantiles: [0.05, 0.95]
train_split: 0.85
model_save_dir: ./models
target_col: Durham New Elvet Bridge - level

lr: 0.0008
batch_size: 1024

activation_function: tanh
predict_difference: false # Need to think a bit more about the implications of this with the ci
num_blocks: 3
dropout: 0.2
ff_dim: 4
normalize_before: false
norm_type: batch
weight_decay: 0.001

# TODO: Also config threshold level probabilities

stations_filepath: ./stations.json