seed: null
prediction_length: 96
context_length: 32
train_epochs: 25
quantiles: [0.05, 0.5, 0.95]
train_split: 0.85
model_save_dir: ./models
target_col: Durham New Elvet Bridge - level (m)

lr: 0.005
batch_size: 512

activation_function: relu
num_blocks: 3
dropout: 0.2
ff_dim: 32
normalize_before: true
norm_type: layer

stations_filepath: ./stations.csv