seed: null
prediction_length: 32
sequence_length: 96
train_epochs: 250
train_split: 0.85
model_save_dir: ./models
target_col: Durham New Elvet Bridge - level
output_channels: 2
quantiles: [0.1, 0.5, 0.9]
thresholds: [0.675]

lr: 0.0003
weight_decay: 0.00003
batch_size: 2048
stations_filepath: ./stations.json

# TODO: Also config threshold level probabilities
