name: Deploy firebase functions
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy firebase functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jsryudev/deploy-firebase-functions@v20.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: durham-river-level
